# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chatbot.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'chatbot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rchatbot.proto\x12\x07\x63hatbot\x1a\x1cgoogle/api/annotations.proto\"\x1e\n\x0b\x43hatRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\" \n\x0c\x43hatResponse\x12\x10\n\x08response\x18\x01 \x01(\t\"q\n\x1aGenerateDescriptionRequest\x12\x14\n\x0cproduct_name\x18\x01 \x01(\t\x12\x15\n\rproduct_price\x18\x02 \x01(\x01\x12\x18\n\x10product_category\x18\x03 \x01(\t\x12\x0c\n\x04tags\x18\x04 \x03(\t\"/\n\x1bGenerateDescriptionResponse\x12\x10\n\x08response\x18\x01 \x01(\t2\xdc\x01\n\x0e\x43hatbotService\x12\x45\n\x04\x43hat\x12\x14.chatbot.ChatRequest\x1a\x15.chatbot.ChatResponse\"\x10\x82\xd3\xe4\x93\x02\n\"\x05/chat:\x01*\x12\x82\x01\n\x13GenerateDescription\x12#.chatbot.GenerateDescriptionRequest\x1a$.chatbot.GenerateDescriptionResponse\" \x82\xd3\xe4\x93\x02\x1a\"\x15/generate-description:\x01*b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chatbot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATBOTSERVICE'].methods_by_name['Chat']._loaded_options = None
  _globals['_CHATBOTSERVICE'].methods_by_name['Chat']._serialized_options = b'\202\323\344\223\002\n\"\005/chat:\001*'
  _globals['_CHATBOTSERVICE'].methods_by_name['GenerateDescription']._loaded_options = None
  _globals['_CHATBOTSERVICE'].methods_by_name['GenerateDescription']._serialized_options = b'\202\323\344\223\002\032\"\025/generate-description:\001*'
  _globals['_CHATREQUEST']._serialized_start=56
  _globals['_CHATREQUEST']._serialized_end=86
  _globals['_CHATRESPONSE']._serialized_start=88
  _globals['_CHATRESPONSE']._serialized_end=120
  _globals['_GENERATEDESCRIPTIONREQUEST']._serialized_start=122
  _globals['_GENERATEDESCRIPTIONREQUEST']._serialized_end=235
  _globals['_GENERATEDESCRIPTIONRESPONSE']._serialized_start=237
  _globals['_GENERATEDESCRIPTIONRESPONSE']._serialized_end=284
  _globals['_CHATBOTSERVICE']._serialized_start=287
  _globals['_CHATBOTSERVICE']._serialized_end=507
# @@protoc_insertion_point(module_scope)
